// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class ThreatCenterApiPigeonCodecReader: FlutterStandardReader {
}

private class ThreatCenterApiPigeonCodecWriter: FlutterStandardWriter {
}

private class ThreatCenterApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ThreatCenterApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ThreatCenterApiPigeonCodecWriter(data: data)
  }
}

class ThreatCenterApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ThreatCenterApiPigeonCodec(readerWriter: ThreatCenterApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ThreatCenterApi {
  func areRootPrivilegesDetected() throws -> Bool
  func areHooksDetected() throws -> Bool
  func isSimulatorDetected() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ThreatCenterApiSetup {
  static var codec: FlutterStandardMessageCodec { ThreatCenterApiPigeonCodec.shared }
  /// Sets up an instance of `ThreatCenterApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ThreatCenterApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let areRootPrivilegesDetectedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_security_toolkit.ThreatCenterApi.areRootPrivilegesDetected\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      areRootPrivilegesDetectedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.areRootPrivilegesDetected()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      areRootPrivilegesDetectedChannel.setMessageHandler(nil)
    }
    let areHooksDetectedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_security_toolkit.ThreatCenterApi.areHooksDetected\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      areHooksDetectedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.areHooksDetected()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      areHooksDetectedChannel.setMessageHandler(nil)
    }
    let isSimulatorDetectedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_security_toolkit.ThreatCenterApi.isSimulatorDetected\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSimulatorDetectedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSimulatorDetected()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSimulatorDetectedChannel.setMessageHandler(nil)
    }
  }
}
